name: Count Access Days

on:
  schedule:
    - cron: '0 17 * * *'  
  workflow_dispatch:      

jobs:
  decrement-days:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decrement Days in Access File
        run: |
          ACCESS_FILE="access"
          TEMP_FILE="access.tmp"

          if [ ! -f "$ACCESS_FILE" ]; then
            echo "File $ACCESS_FILE tidak ditemukan!"
            exit 1
          fi

          > "$TEMP_FILE"  
          while IFS= read -r line; do
            if [[ -z "$line" ]]; then
              continue
            fi

            IP=$(echo "$line" | awk '{print $1}')
            COMMENT=$(echo "$line" | cut -d'#' -f2-)

            if [[ "$COMMENT" =~ ([0-9]+)day ]]; then
              DAYS=${BASH_REMATCH[1]}
              NEW_DAYS=$((DAYS - 1))

              if [ "$NEW_DAYS" -le 0 ]; then
                echo "Menghapus IP $IP karena masa berlaku habis."
                continue 
              else
                NEW_COMMENT=$(echo "$COMMENT" | sed "s/${DAYS}day/${NEW_DAYS}day/")
                echo "$IP #$NEW_COMMENT" >> "$TEMP_FILE"
              fi
            else
              echo "$line" >> "$TEMP_FILE"
            fi
          done < "$ACCESS_FILE"

          mv "$TEMP_FILE" "$ACCESS_FILE"
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - uses: stefanzweifel/git-auto-commit-action@v5

